### ISSUE TITLE
Is this repos still maintained?

### ISSUE THREAD

**Issue by dongwangdw** [hyperledger/fabric-cli#38]
Not sure if this maintained? If not, why abandoned?

I think the cmd is good idea. Is there any other consideration not to keep on this project.

**Comment by lehors** [comment]
Hi, I wouldn't say that it is abandoned. Some people use it and PRs are welcome. The last one was merged in a few months ago. But it's clear that there is currently no significant development effort going on. I think this is primarily due to the main developers having changed jobs and moved on to other things.

**Comment by dongwangdw** [comment]
Ok. Thanks. I think this cli is great, hoping it will be better and better.
